### ISSUE TITLE
Synchronize Gmail to MySQL database with yii2-google-apiclient

### ISSUE THREAD

**Issue by nikdejan** [machour/yii2-google-apiclient#12]
What would be the best approach? Where to put code?
Here is my idea:
Three tables in mysql: threads, messages and one table to store historyId of last synchronization.
Put the code in controller/action and set up a cron job which will execute the code every 5 minutes.
Code will call users.history: list with type "messageAdded" with startHistoryId from previous synchronization and label INBOX. Then a batch of users.messages: get to store them in database. 
This will get all received email messages. Messages will be sent exclusively from application so they could be stored in database during send process. 
Once in 24 hours I would do full comparison of mailbox and database just to check that everything is ok.
Any suggestions? Some example solution/code maybe?

**Comment by machour** [comment]
@nikdejan I only used the gmail API to fetch the number of unread messages in my apps, and never actually stored messages. 

You'll have to figure this one on your own ;)
