### ISSUE TITLE
Error refreshing the OAuth2 token

### ISSUE THREAD

**Issue by freetibet000** [machour/yii2-google-apiclient#13]
Hello.
I try to use your library but i have issues with token refreshing.
After generating JSON file by your console helper it works perfect some time.
But from 1-2 hours i am getting next error:

Google_Auth_Exception
Error refreshing the OAuth2 token, message: '{
"error": "invalid_request",
"error_description": "Missing required parameter: refresh_token"
}'

**Comment by machour** [comment]
Hi, this repository is outdated and you should be using idk/yii2-google-apiclient instead
