### ISSUE TITLE
Problems with Access Token

### ISSUE THREAD

**Issue by newscloud** [machour/yii2-google-apiclient#2]
I tried following your example. Thank you for putting it together. The Gmail API credentials process is impossibly complicated.

I moved the files and renamed them into frontend runtime ... (from console) ... both auth.json which I downloaded from Google and then gmail.json which was generated by your console script

But it fails here...
 if (! isset($token['access_token'])) {
      throw new Google_Auth_Exception("Invalid token format");

http://screencast.com/t/GEaoCZeuD2PY

I'm not sure what I've done wrong. Your script leaves a lot of open steps to guess at.

**Comment by newscloud** [comment]
Do you have code example where a single application can allow users to click an authorization button and authorize their google account for mail access? And to refresh tokens as needed?

I'd like to make my app support multiple users easily from within one web app (site) not using the console for each user.

**Comment by machour** [comment]
Hi @newscloud do you still experience this issue ? If so, could you elaborate a simple use case scenario failing ,

**Comment by newscloud** [comment]
Hi, I think gave up last fall.

**Comment by nikdejan** [comment]
Now I have a same problem as @newscloud 
Edit: Problem solved for me. I made two copies of the fail which application created: gmail.json and auth.json and put them both in runtime/google-apiclient folder.
This google api is tooo complicated!
