### ISSUE TITLE
Error when  /configure sub command - 'Undefined property: stdClass::$client_secret'

### ISSUE THREAD

**Issue by carlos-andres** [machour/yii2-google-apiclient#3]
Greetings, 

i  got the following error trying to generate configuration files.. thanks in advance

![image](https://cloud.githubusercontent.com/assets/5489747/19786392/55a5f414-9c63-11e6-96b7-98df630b8757.png)

**Comment by machour** [comment]
Can you make sure your client_secret.json file is ok ?

**Comment by carlos-andres** [comment]
Good Day @machour thanks for your response, and here´s the deal:

when i check mi google console.. there is 2 options,  the first one is OAuth 2.0 client IDs, and the other Service account.

![image](https://cloud.githubusercontent.com/assets/5489747/19806133/62f63716-9cde-11e6-8ef3-17a775c6ed9f.png)

when i try with the "Web application" account type i got another error but i thing is a mistake from me.. 

![image](https://cloud.githubusercontent.com/assets/5489747/19806224/1163da24-9cdf-11e6-9823-f4e6c20946ca.png)

Reading the documentation i need to work with service account, so when i check both .json files i see a lot of diffs. but i dont know what i mss.  And when i try to run configure with service account json got the error from past post. 

"... server-side authorization to display your Google Analytics data to users without granting them access to your Google Analytics account."
https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/

![image](https://cloud.githubusercontent.com/assets/5489747/19806327/cf84b802-9cdf-11e6-9db3-8ecd567e87c5.png)

**Comment by machour** [comment]
@carlos-andres do you still get this issue ?

**Comment by machour** [comment]
Feel free to reopen if this still happens
