### ISSUE TITLE
Issue trying to use freebusy method

### ISSUE THREAD

**Issue by mavelar** [machour/yii2-google-apiclient#9]
I have a problem when I request a query in freebusy class, doesnt get any calendar in response data.

here my piece of code:

```
$service = Yii::$app->calendar->getService();
$calendarItems = [];

$data = $request->post();

$freebusy = new \Google_Service_Calendar_FreeBusyRequest();

$timeMin = new \DateTime('2017-07-13 08:00:00');
$timeMax = new \DateTime('2017-07-13 17:00:00');

$freebusy->timeMin = $timeMin->format(\DateTime::ISO8601);
$freebusy->timeMax = $timeMax->format(\DateTime::ISO8601);
$freebusy->timeZone = 'America/Tegucigalpa';

$freebusyItems = [];

foreach($data['calendars'] as $calendarId) {
  $freebusyItem = new \Google_Service_Calendar_FreeBusyRequestItem();
  $freebusyItem->id = $calendarId;
  $freebusyItems[] = $freebusyItem;
}

$freebusy->items = $freebusyItems;

$response['data'] = $service->freebusy->query($freebusy);
```

My response is this:

```
{
  "kind": "calendar#freeBusy",
  "timeMax": "2017-07-13T17:00:00.000Z",
  "timeMin": "2017-07-13T08:00:00.000Z"
}
```

Any help about this? please I need to fix this ASAP.

Thanks

**Comment by machour** [comment]
Hi @mavelar, this seems to be a problem with your code, or your Google Api call and have nothing to do with my library (which does its job correctly as you are connected).
Maybe check the content of your $freebusyItems variable and check if your foreach added calendars ids ? Good luck anyways :)

Closing this as unrelated.

**Comment by mavelar** [comment]
Thanks, I will check that then.

**Comment by mavelar** [comment]
For your record, the issue was solve using the toSimpleObject() method after query response.

```
        ...
	$freebusyResponse = $service->freebusy->query($freebusy);

	$response['data'] = $freebusyResponse->toSimpleObject();
        ...
```

I hope could help to others.

**Comment by machour** [comment]
Thank you for sharing that !
